// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYTA0DVHUywxwsqUKfVWuXtj3LlvrwBEQ',
    appId: '1:141176886677:web:6365fe64b4e4fc7010929c',
    messagingSenderId: '141176886677',
    projectId: 'jmc-capstone',
    authDomain: 'jmc-capstone.firebaseapp.com',
    storageBucket: 'jmc-capstone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0344F0vpqdbgt2XVTPrUjucPTXX3zMfg',
    appId: '1:141176886677:android:f4b41b41376e06e310929c',
    messagingSenderId: '141176886677',
    projectId: 'jmc-capstone',
    storageBucket: 'jmc-capstone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVu64bmt0r2qF7YTZXA8IuO9vxi9Ntls',
    appId: '1:141176886677:ios:622677ffa18ecf3710929c',
    messagingSenderId: '141176886677',
    projectId: 'jmc-capstone',
    storageBucket: 'jmc-capstone.firebasestorage.app',
    iosBundleId: 'com.example.jmc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNVu64bmt0r2qF7YTZXA8IuO9vxi9Ntls',
    appId: '1:141176886677:ios:622677ffa18ecf3710929c',
    messagingSenderId: '141176886677',
    projectId: 'jmc-capstone',
    storageBucket: 'jmc-capstone.firebasestorage.app',
    iosBundleId: 'com.example.jmc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYTA0DVHUywxwsqUKfVWuXtj3LlvrwBEQ',
    appId: '1:141176886677:web:d9a6b1221182fe9a10929c',
    messagingSenderId: '141176886677',
    projectId: 'jmc-capstone',
    authDomain: 'jmc-capstone.firebaseapp.com',
    storageBucket: 'jmc-capstone.firebasestorage.app',
  );

}